trigger:
  branches:
    include:
      - releases/*

pr:
  branches:
    include:
      - main

jobs:
  - job: ReleaseTests
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 30

    strategy:
      matrix:
        latest:
          python-version: 3.11

    steps:
      - template: templates/env-setup.yaml
      - template: templates/run-precommits.yaml
      - template: templates/run-optional-tests.yaml
        parameters:
          testSuite: e2e
      - template: templates/run-optional-tests.yaml
        parameters:
          testSuite: notebook
